### server port
server:
  port: 8081

#Keycloak Configuration
keycloak:
  securityConstraints:
    - securityCollections:
      - patterns:
          - /customers/*
      authRoles:
        - admin
        - user
    - securityCollections:
      - name: login-app-admin
        patterns:
          - /admin/*
      authRoles:
        - admin
  auth-server-url: http://localhost:8180/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  principal-attribute: preferred_username
  always-refresh-token: true
